dap:
    project-path: /home/napbad/Project/dap-dev-main/
    log-path: /home/napbad/Project/dap-dev-main/logs/
    test:
        dap-main-path: compiler/cmake-build-debug/dap_compiler
        target-directory: tests/dap_test
        source-runtime-dir: dap/runtime
        dap-main-argument:
        D_DEBUG: True