dap:
    project-path: /home/napbad/Project/dap-dev-main/
    log-path: /home/napbad/Project/dap-dev-main/logs/
    test:
        dap-main-path: compiler/cmake-build-debug/dap_compiler
        target-directory: tests/dap_test/
        source-runtime-dir: dap/runtime/
        dap-main-argument: 
        dap-build-executable-directory: tests/build/
        dap-build-executable-name: main_proj
        dap-source-runtime-dir: dap/runtime/
        debug-mode: False
        D_DEBUG: True
